#       Copyright 2017-2021 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Default values for stocktrader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  auth: basic
  replicas: 1
  autoscale: false
  monitoring: true
  ingress: false
  route: true
  healthCheck: true
  jsonLogging: false
  istio: false
  istioNamespace: istio-system
  specifyCerts: false
  certs: <your SSL certificates>
database:
  kind: db2
  host: db2trader1-ibm-db2oltp-dev
  port: 50000
  id: db2inst1
  password: db2inst1
  db: trader
broker:
  image:
    repository: ibmstocktrader/broker
    tag: latest
  url: http://{{ .Release.Name }}-broker-service:9080/broker
portfolio:
  image:
    repository: ibmstocktrader/portfolio
    tag: latest
  url: http://{{ .Release.Name }}-portfolio-service:9080/portfolio
stockQuote:
  image:
    repository: ibmstocktrader/stock-quote
    tag: latest
  url: http://{{ .Release.Name }}-stock-quote-service:9080/stock-quote
  apiConnect: https://api.us.apiconnect.ibmcloud.com/jalcornusibmcom-dev/sb/stocks
  iexTrading: https://cloud.iexapis.com/stable/stock
  iexApiKey: <your IEX API key>
trader:
  enabled: true
  image:
    repository: ibmstocktrader/trader
    tag: latest
tradr:
  enabled: false
  image:
    repository: ibmstocktrader/tradr
    tag: latest
account:
  enabled: false
  image:
    repository: ibmstocktrader/account
    tag: latest
  url: http://{{ .Release.Name }}-account-service:9080/account
messaging:
  enabled: false
  image:
    repository: ibmstocktrader/messaging
    tag: latest
  notification:
    url: http://{{ .Release.Name }}-notification-service:9080/notification
notificationSlack:
  enabled: false
  image:
    repository: ibmstocktrader/notification-slack
    tag: latest
notificationTwitter:
  enabled: false
  image:
    repository: ibmstocktrader/notification-twitter
    tag: latest
tradeHistory:
  enabled: false
  image:
    repository: ibmstocktrader/trade-history
    tag: latest
  url: http://{{ .Release.Name }}-trade-history-service:9080/trade-history
collector:
  enabled: false
  image:
    repository: ibmstocktrader/collector
    tag: latest
  url: http://{{ .Release.Name }}-collector-service:9080/collector
looper:
  enabled: false
  image:
    repository: ibmstocktrader/looper
    tag: latest
  url: http://{{ .Release.Name }}-looper-service:9080/looper
jwt:
  issuer: http://stock-trader.ibm.com
  audience: stock-trader
oidc:
  clientId: <your client id>
  clientSecret: <your client secret>
  discoveryUrl: <your discovery endpoint URL>
ldap:
  host: bluepages.ibm.com
  port: 389
  baseDN: o=ibm.com
  realm: BluePages
watson:
  id: apikey
  passwordOrApiKey: <your API key>
  url: https://gateway.watsonplatform.net/tone-analyzer/api/v3/tone?version=2017-09-21&sentences=false
odm:
  id: odmAdmin
  password: odmAdmin
  url: http://odmtrader1-ibm-odm-dev:9060/DecisionService/rest/ICP_Trader_Dev_1/determineLoyalty
mq:
  host: mqtrader1-mqtrader1
  port: 1414
  id: app
  password: ""
  queueManager: stocktrader
  queue: NotificationQ
  channel: DEV.APP.SVRCONN
redis:
  urlWithCredentials: redis://<your credentials>@redistrader1-ibm-redis-ha-dev-master-svc:6379
  cacheInterval: 60
openwhisk:
  id: <your id>
  password: <your password>
  url: https://openwhisk.ng.bluemix.net/api/v1/namespaces/jalcorn%40us.ibm.com_dev/actions/PostLoyaltyLevelToSlack
twitter:
  consumerKey: <your consumer key>
  consumerSecret: <your consumer secret>
  accessToken: <your access token>
  accessTokenSecret: <your access token secret>
kafka:
  address: <your Kafka proxy service>:30000
  topic: stocktrader
  user: token
  apiKey: <your API key>
cloudant:
  url: <your Cloudant URL>
  id: <your Cloudant ID>
  password: <your Cloudant Password>
  database: <your Cloudant Account database name>
  collector: <your Cloudant Collector database name>
mongo:
  ip: <your Mongo IP>
  port: 27017
  user: <your Mongo user>
  password: <your Mongo password>
  database: <your Mongo database>
  authDB: <your Mongo auth database>
s3:
  enabled: false
  bucket: stock-trader
  location: <your S3 location>
  endpointUrl: <your S3 endpoint URL>
  resourceInstanceId: <your S3 CRN>
  apiKey: <your S3 API Key>
